# Generated by Django 5.2.12 on 2026-03-16 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='rule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='step',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='next_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_rules', to='workflows.step'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='step',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='input_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='start_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_start', to='workflows.step'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='rule',
            table='rules',
        ),
        migrations.AlterModelTable(
            name='step',
            table='steps',
        ),
        migrations.AlterModelTable(
            name='workflow',
            table='workflows',
        ),
    ]
