# Generated by Django 5.2.12 on 2026-03-16 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
        ('workflows', '0002_alter_rule_options_alter_step_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveField(
            model_name='execution',
            name='current_step',
        ),
        migrations.AddField(
            model_name='execution',
            name='current_step_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='retries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execution',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='execution',
            name='triggered_by',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='execution',
            name='workflow_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='execution',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='execution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='workflows.workflow'),
        ),
        migrations.AlterModelTable(
            name='execution',
            table='executions',
        ),
    ]
